config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  
  resources :properties  
  resources :uploads

  devise_for :accounts, controllers: {omniauth_callbacks: 'omniauth'}
  root to: 'home#main'
  resources :companies  do
    resources :properties, only: [:index, :show, :new]
  end


  Rails.application.routes.draw do
  resources :companies
    mount ImageUploader.derivation_endpoint => "derivations/image"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">Home Guru</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <%= link_to "Log Out", destroy_account_session_path,  method: :delete, class: "nav-link" %>       
        </li>
      </ul>
    </nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Your Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      <% if account_signed_in?%>
      <%= link_to 'Dashboard', dashboard_path, class:"nav-link" %>
      <% else%>
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Properties', properties_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'Companies', companies_path, class:"nav-link" %>
      </li>         
      
      <% if account_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log Out", destroy_account_session_path,  method: :delete, class: "nav-link" %>
      </li>
      <% else%>
      <li class="nav-item">
        <%= link_to "Sign In", new_account_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
      </li>
       
      <% end%>
    </ul>
    <%# avatar %>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <%= link_to dashboard_path, class: "nav-link" do %>
                <i class="fas fa-house-user"></i>
                  Dashboard <span class="sr-only">(current)</span>
                    <% end %>
              </li>
              <li class="nav-item">
                 <%= link_to properties_path, class: "nav-link" do %>
                 <i class="fas fa-home"></i>
                  Listings
                <% end%>
              </li>
              <li class="nav-item">
                 <%= link_to edit_account_registration_path, class: "nav-link" do %>
                 <i class="fas fa-home"></i>
                  Account
                <% end%>
              </li><li class="nav-item">
                 <%= link_to companies_path, class: "nav-link" do %>
                 <i class="fas fa-home"></i>
                  Companies
                <% end%>
              </li><li class="nav-item">
                 <%= link_to properties_path, class: "nav-link" do %>
                 <i class="fas fa-home"></i>
                  Listings
                <% end%>
              </li>
             
            </ul>
          </div>
        </nav>