config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  
  resources :properties  
  resources :uploads

  devise_for :accounts, controllers: {omniauth_callbacks: 'omniauth'}
  root to: 'home#main'
  resources :companies  do
    resources :properties, only: [:index, :show, :new]
  end


  Rails.application.routes.draw do
  resources :companies
    mount ImageUploader.derivation_endpoint => "derivations/image"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
class Property < ApplicationRecord
    include ImageUploader::Attachment(:image)   
    belongs_to :account
    belongs_to :company

    scope :latest, -> { order created_at: :desc}
    # Ex:- scope :active, -> {where(:active => true)}
    
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :set_property, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_account!, only: [:new,:create,:destroy]
    before_action :authorize, only:[:edit, :update, :destroy]
    
    
    
  
    def index
      if params[:company_id]
        @properties = Company.find(params[:company_id]).properties
      else
        @properties = Property.all
      end
    end
    
     
    
    def show
    end  

    def remax
      
    end
    
    
    def new
      @property = Property.new(company_id: params[:company_id])
    end
  
    
    def edit
    end
  
   
    def create
      @property = Property.new(property_params)
      @property.account_id = current_account.id
      
      
      
  
      if @property.save
        redirect_to @property, notice: 'Property was successfully created.'
      else
        render :new
      end
    end
  
    
    def update
      if @property.update(property_params)
        redirect_to @property, notice: 'Property was successfully updated.'
      else
        render :edit
      end
    end
  
   
    def destroy
      @property.destroy
      redirect_to properties_url, notice: 'Property was successfully destroyed.'
    end
  
    private      
      def set_property      
        @property = Property.find(params[:id])
      end
  
      
      def property_params
        params.require(:property).permit(:address, :price, :rooms, :bathrooms,:image,:accounts,:company_id,:company)
      end

      def authorize
        
      
        
        if current_account.id == @property.account_id
        else
          flash[:error] = "You do not have authorization to edit this Property" 
            
            redirect_to properties_path
        end
      end
      
end

app/helpers/properties_helper.rb
module PropertiesHelper

    def small_thumb(property)
        image_tag property.image_url(:small), style: "width:250px; border: 5px solid black;height: fit-content; "
    end

    def prop_photo(property)
        image_tag property.image_url
    end
    
    def profile_picture
        image_tag   acct.image_remote_url
    end

    def avatar
        image_tag current_account.image, style:"width: 30px; height: 30px; border-radius: 50%;"
    end
    


   
    
    
end

app/views/properties/_form.html.erb
<%= form_for(property) do |f| %>
<%= render "layouts/validation", item: @property %>
  
  
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rooms %>
    <%= f.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :bathrooms %>
    <%= f.number_field :bathrooms, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= f.label :photo %>
    <%= f.hidden_field :image, value: @photo&.cached_image_data %>
    <%= f.file_field :image %>
  </div>

  <% if property.company_id.nil? %> 
    <div class="form-group">
      <%= f.label :company %> <br />
      <%= f.collection_select(:company_id, Company.all, :id, :name, { :prompt=>"Select a Company" }, { :class => "form-control" }) %>
    <% else %>
      <%= f.hidden_field :company_id %>
    </div>
    <% end %>


  

  <div class="actions">
    <%= f.submit "Save Listing", class: "btn btn lg  btn-success" %>
  </div>
<% end %>

app/views/properties/_latest_listings.html.erb
<% @properties.each do |p| %>
    <div class="col-sm-3">
                  
            <div class="card">
                <div class="post">
                    <div class="header_post">
                    <%= prop_photo p  %>
                    </div>

                    <div class="body_post">
                        <div class="post_content">

                            <h1><%=  p.company.name%></h1>
                            <p><%= p.address %>.</p>

                            <div class="container_infos">
                                <div class="postedBy">
                                    <span>View Listing</span>
                                    <%= link_to "Lisiting", property_path(p) %>
                                </div>

                               
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
    </div>
<% end%>

app/views/properties/edit.html.erb
<h3>Editing Property</h3>
<%=flash[:error] %>


<%= render 'form', property: @property %>

app/views/properties/index.html.erb
<%=flash[:error] %>

<h3>Properties</h3>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.company.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class:"btn btn-success" %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<%=flash[:error] %>


<div class="listing-header" style="object-fit:cover; background-image:url('<%= @property.image_url(:large) %>')"></div>


<div class='container-fluid'>
    <div id="HomeDetails" class="HomeDetails"><div class="Collapsable"><div class="Collapsable__maxHeightContent" style="max-height: 100px;"><div class="HomeDetails__detailsText">Welcome to the Huntsford Farm Community! Don't miss this open floor plan Townhome that features a 2 story great room with a palladium window. The kitchen offers plenty of cabinet &amp; counter space with eat-in dinette area leading to sliding glass doors &amp; rear deck. A convenient first floor laundry area leads to a nice sized 2 car attached garage. The first floor bedroom or office space features a closet, attached private bath &amp; french doors. Retreat to the spacious master bedroom that offers 2 closets (1 closet is a nice sized walk in closet) vaulted ceilings &amp; beautiful palladium window overlooking the front of a beautiful neighborhood. This property won't last! Schedule your private showing and make an offer today!</div></div><div class="Collapsable__label"><div class="icon icon-drop-down-arrow"></div>See More</div></div><div class="HomeDetails__mlsSource">Source: YES MLS</div><div class="HomeDetails__mlsNumber">MLS#: 4238531</div></div>

  <div class='row'>
  <p class='mb-0'> <%= @property.address %> </p>
        <p> <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "For Sale" %> </p>
    <div class= 'col-sm-8'>
    <p class='mb-0'> <%= @property.address %> </p>
        <p> <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "For Sale" %> </p>
     <div class="row">
      <div class='col-lg-6'>
        <p class='mb-0'> <%= @property.address %> </p>
        <p> <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "For Sale" %> </p>
      </div>
     </div>
    
    

    

    <p>
      <strong>Rooms:</strong>
      <%= @property.rooms %>
    </p>

    <p>
      <strong>Bathrooms:</strong>
      <%= @property.bathrooms %>
    </p>
    <%# image_tag @property.image_url, style: "width:200px; display:block" %>

    <%= link_to 'Edit', edit_property_path(@property) %> |
    <%= link_to 'Back', properties_path %>
    </div>
  </div>
</div>