config/routes.rb
Rails.application.routes.draw do
  resources :companies
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  
  resources :properties  
  resources :uploads

  devise_for :accounts, controllers: {omniauth_callbacks: 'omniauth'}
  root to: 'home#main'
  resources :companies  do
    resources :properties, only: [:index, :show, :new]
  end


  Rails.application.routes.draw do
  resources :companies
    mount ImageUploader.derivation_endpoint => "derivations/image"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
    include ImageUploader::Attachment(:image)
    has_many :accounts ,through: :properties
    has_many :properties
    validates_presence_of :name, :address, :website
    validates_length_of :year_founded, is: 4,  message: "Year must be in YYYY"
    enum size: [:"0-50", :"51-200", :"201-500", :"501-1000", :"1000+"]
    enum revenue: [:"Below 1 Million", :"1 to 10 Million", :"10 to 100 Million", :"More than 100 Million"]
    
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    before_action :set_company, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_account!, only: [:new,:create,:destroy]
    before_action :authorize, only:[:edit, :update, :destroy]

    
    def index
      @companies = Company.all
      
    end
  
 
    def show
        set_company
    end
  

    def new
      @company = Company.new
    end
  
   
    def edit       
    end
  
    
    def create
      @company = Company.new(company_params)
      @company.account_id = current_account.id
  
      if @company.valid?
        @company.save
        redirect_to @company
      else
        render :new
      end
    end
  
  
   
    def update      
        if @company.update(company_params)
            redirect_to @company, notice: 'Company was successfully updated.'
        else
            render :edit          
      end
    end
  
   
    def destroy
      accounts = Account.where(company_id: @company.id)
      accounts.each do |accounts|
        accounts.update({
          company_id: 0
        })
      end
      @company.destroy      
    end
    
  
    private
      def set_company
        @company = Company.find(params[:id])
      end
  
      def company_params
        params.fetch(:company, {}).permit(:name, :website, :address, :year_founded, :size, :revenue, :synopsis,:image,:accounts)
      end

      def authorize
        if current_account.id == @company.account_id
        else
          flash[:error] = "You do not have authorization to edit this Company" 
          redirect_to companies_path
        end
             
    end
  end

app/helpers/companies_helper.rb
module CompaniesHelper

    

end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |f| %>
  <div class="container">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :website %>
      <%= f.text_field :website, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :address %>
      <%= f.text_field :address, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :year_founded %>
      <%= f.text_field :year_founded, :class => "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :size %>
      <%= f.select(:size, Company.sizes.keys, {}, { :class => "form-control" }) %>
    </div>

    <div class="form-group">
      <%= f.label :revenue %>
      <%= f.select(:revenue, Company.revenues.keys, {}, { :class => "form-control"}) %>
    </div>

    <div class="form-group">
      <%= f.label :synopsis %>
      <%= f.text_field :synopsis, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :photo %>
      <%= f.hidden_field :image, value: @photo&.cached_image_data %>
      <%= f.file_field :image %>
    </div>

    <% if company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.submit :class=> "btn btn-success" %>
      <%= link_to 'Back', companies_path, :class=>"btn btn-secondary"%>
    </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="container" style="margin-top:50px">
  <h1>Editing Company</h1>
  <%= render 'form', company: @company %>
</div>

app/views/companies/index.html.erb
<%=flash[:error] %>

<div class="container">
  <h1>Companies</h1>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Website</th>
        <th>Address</th>
        <th>Size</th>
        <th>Revenue</th>
        <th>Synopsis</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @companies.each do |company| %>
        <tr>          
          <td><%= company.name %></td>
          <td><%= company.website %></td>
          <td><%= company.address %></td>
          <td><%= company.size %></td>
          <td><%= company.revenue %></td>
          <td><%= company.synopsis %></td>

          
            <td><%= link_to 'Edit', edit_company_path(company) %></td>
            <td><%= link_to 'Show', company_path(company) %></td>

          
            <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <% if session[:role] != 'buyer' %>
    <%= link_to 'New Company', new_company_path, :class => "btn btn-success" %>
  <% end %>
</div>

app/views/companies/new.html.erb
<div class="container">
  <div class="card" style="width: 36rem; margin-top: 50px;" >
    <div class="card-header">
      Company
    </div>
    <div class="card-body">
      <%= render 'form', company: @company %>
    </div>
  </div>
  </div>
</div>

app/views/companies/show.html.erb
 <div class="company-header" style="background-image:url('<%= @company.image_url(:large) %>')"></div>

 <div class='container-fluid'>
 

    <p>
      <strong>Name:</strong>
      <%= @company.name %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= @company.website %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @company.address %>
    </p>

    <p>
      <strong>Size:</strong>
      <%= @company.size %>
    </p>

    <p>
      <strong>Year Founded:</strong>
      <%= @company.year_founded %>
    </p>

     <p>
      <strong>Revenue:</strong>
      <%= @company.revenue %>
    </p>

     <p>
      <strong>Synopsis:</strong>
      <%= @company.synopsis %>
    </p>


    

    <%= link_to 'Edit', edit_company_path(@company) %> |
    <%= link_to 'Back', companies_path %> |
    <%= link_to  'New listing', new_company_property_path(@company) %> |
    <%= link_to  'Listings', company_properties_path(@company) %> 
    


    
</div>